Dev reg hie merged dev
FZJ-INM1-BDA/siibra-explorer pull request #1091
Opened 2021-11-02 12:11 UTC by fsdavid

2021-11-02 13:54 UTC, xgui3783 commented
the tree is slightly misaligned (by maybe 0.5 character)

current:
![Screenshot from 2021-11-02 14-54-20](https://user-images.githubusercontent.com/19381783/139860890-175faeb2-696c-4f62-b7f2-f280bd9dabc8.png)

this update:

![Screenshot from 2021-11-02 14-53-21](https://user-images.githubusercontent.com/19381783/139860908-a990e486-51b3-4708-920a-76e2c6ab4cf1.png)

2021-11-02 14:00 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                             marginTop: - lineHeight/2 + 'px'}"
please use a pipe for this

2021-11-02 14:00 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                        [style.height]="lineHeight + 'px'"
ditto above

2021-11-02 14:01 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.spec.ts
> +});
ideally there should be more tests than just `should create`

2021-11-02 14:02 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +  public _searchString: string
set to private? no need to be public i think?

2021-11-02 14:05 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +  filterChanged(filterText: string) {
this function in general is very confusing. 

I know what it tries to do at the very end, but perhaps we can clean it up a little bit

2021-11-02 14:09 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +}
I think I know why we keep a reference to `selectedRegion`, as it will two way bind to the selected region. 

Still, I think it's less brittle if we keep a single source of truth, and inject selected region as an input, or get it from the store (if the store is injected already).

It would also simplify `toggleSelection` method

2021-11-02 14:10 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/regionHierarchy.template.html
> +
can you remove all references to `flat-tree-component`?

I don't think it's used anywhere else but here.

2021-11-02 14:10 UTC, xgui3783 commented on src/components/components.module.ts
> +    HighlightPipe,
I didn't think highlight pipe is needed in `component.module`?

2021-11-16 13:40 UTC, fsdavid commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +<!--                    </button>-->
This is the navigate button. As I know, we will get region positions easier, we will just uncomment. I will add ToDo

2021-12-01 21:38 UTC, fsdavid commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                             marginTop: - lineHeight/2 + 'px'}"
Using a directive would be acceptable?

2021-12-03 15:46 UTC, fsdavid commented
@xgui3783 could you please have a look? I've made the changes.

2021-12-03 16:09 UTC, xgui3783 commented
will look more closely at the code later, but immediately, 2 things jump out at me:

![Screenshot from 2021-12-03 17-05-36](https://user-images.githubusercontent.com/19381783/144634463-62ac9f59-9e98-4905-9653-1cbe16d94bf0.png)

- the tree is offset (see https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1091#issuecomment-957627022)
- I really do not like the selected region, how it is bordered. Why can't we still have selected = yellow text?

2021-12-03 16:33 UTC, fsdavid commented
> * the tree is offset 
Sorry, what do you mean with offset? space between the collapse arrow and the buttons?
> * I really do not like the selected region, how it is bordered. Why can't we still have selected = yellow text?
Sure we can have yellow color for selected regions

2021-12-03 17:57 UTC, xgui3783 commented
> Sorry, what do you mean with offset? space between the collapse arrow and the buttons?

offset between arrow and the tree trunk and arrow. See screenshot below.

![highlight_tree](https://user-images.githubusercontent.com/19381783/144650301-16666b33-a7b9-489e-9d7a-a46af51dbb0b.png)

2021-12-06 17:14 UTC, xgui3783 commented
still have to review the code, sorry, didn't get a chance to do that.

but re: tree branches, it's now poking out from the bottom =( 

also, I would reconsider single click on tree branch == collapse/expand tree. We want to reintroduce selection of higher hierarchy regions in the future (see #1008 ) 

re: go there icon in tree view:
- it sometimes does not work
- it doesn't look good at all

I say let's take it out for the time being

2021-12-06 23:46 UTC, fsdavid commented
> also, I would reconsider single click on tree branch == collapse/expand tree. We want to reintroduce selection of higher hierarchy regions in the future (see #1008 )

Yes, I agree. After multi-selection, we can use checkboxes. Then single click will select parent regions and collapse/expand will happen only on arrow click (when checkbox will be there, it will very clear that single click will select the region instead of collapsing).

2021-12-07 09:09 UTC, xgui3783 commented
> Yes, I agree. After multi-selection, we can use checkboxes. Then single click will select parent regions and collapse/expand will happen only on arrow click (when checkbox will be there, it will very clear that single click will select the region instead of collapsing).

As such, I don't think we should introduce a different interaction to the parent region.

2021-12-07 09:39 UTC, xgui3783 requested changes
mostly small cosmetic changes, except the big block of code in tree component

I can't help but to think there must be an easier way to deal with the children

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/module.ts
> +    RegionTreeComponent,
I am half half on naming this component something generic and keep it as something like `SearchableTreeModule` or s th

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                            </mat-icon>
see comment about `go to` region

the icon is not very pleasant, and half o the region doesn't work. 

I say we remove this

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                <div>
why do we need a naked div here?

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.html
> +                </button>
I am not too sure of using button. I feel it's closer to a list rather than a button (with hoverable/clickable state, that is)

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +      ((node: any, level: number) => ({
can you type the node object here?

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +  correctToggledItems() {
I see you extracted the function here, but I still struggle to understand what this function is suppose to do. 

is it suppose to add `missBorderPaintingLevels` property and nothing else?

also, (relevant generally), these functions should be private, as it is not called outside the component.

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +  filter = (array, text) => {
should be made private

and please add typing

2021-12-07 09:39 UTC, xgui3783 commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +    event.preventDefault()
why is preventdefault needed here? (I genuinely do not know/forgot)

2021-12-07 09:39 UTC, xgui3783 commented on src/environments/environment.common.ts
> +  BS_REST_URL: 'https://siibra-api-stable.apps.hbp.eu/v1_0',
when it gets deployed on dev cluster, (I think) it gets overwritten to be latest.

I don't mind on our dev machine it targets stable, but just keep in mind, we may get a lot of "it works on my machine" issue down the line.

2021-12-07 09:39 UTC, xgui3783 commented on src/sharedModules/angularMaterial.module.ts
> +    MatRadioModule
we are no longer using radio? please remove

2021-12-07 09:39 UTC, xgui3783 commented on src/util/util.module.ts
> +    SafeStylePipe,
we can probably remove safestyle pipe, it is not used anywhere

2021-12-08 14:32 UTC, fsdavid commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +      ((node: any, level: number) => ({
It is a region object. Do we have some interface or type for the region?

2021-12-08 14:39 UTC, xgui3783 commented
I figured as much.

Don't worry about typing for the time being, but do try to:

- rename component so it's agnostic (remove all reference to region)
- move to its own module

I can/will take a look at the implementation / write interfaces once you
are done

On Wed, Dec 8, 2021 at 3:33 PM fsdavid ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> <https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1091#discussion_r764919105>
> :
>
> > +    this.filterChanged(ss)
> +  }
> +  get searchString() { return this._searchString }
> +
> +  @Output() public selectRegion: EventEmitter<any> = new EventEmitter()
> +  @Output() public navigateToRegion: EventEmitter<any> = new EventEmitter()
> +
> +  public treeControl: FlatTreeControl<any> = new FlatTreeControl<any>((e => e.level), (e => e.hasChildren))
> +  public dataSource: MatTreeFlatDataSource<any, any>
> +  public lineHeight = 20
> +
> +
> +
> +  public treeFlattener =
> +    new MatTreeFlattener<any, any>(
> +      ((node: any, level: number) => ({
>
> It is a region object. Do we have some interface or type for the region?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1091#discussion_r764919105>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AET34F5B272VOM5ORSMV32DUP5UBZANCNFSM5HGJVFKQ>
> .
>

2021-12-08 14:50 UTC, fsdavid commented on src/atlasComponents/parcellation/regionHierachy/region-tree/region-tree.component.ts
> +  correctToggledItems() {
Yes, I'll change name to `addmissBorderPaintingLevels`

2022-03-22 08:06 UTC, xgui3783 commented
superceded by #1169 specifically e0088c090cf5890d0f0def47170326c7d573fb32

2022-03-22 08:06 UTC, closed without merging