Do not hide annotations with parcellation
FZJ-INM1-BDA/siibra-explorer pull request #1092
Opened 2021-11-02 13:07 UTC by fsdavid

2021-11-02 13:21 UTC, xgui3783 commented
does this PR deal with the `q` short cut?

2021-11-02 13:22 UTC, fsdavid commented
Yes, I will mention it

2021-11-02 13:37 UTC, fsdavid commented
Keeping a list of all segmentation ng volumes would not be too buggy for the feature? 

I thought, while hiding parcellation, we have 3 ways to make it done, 1 - keep a list of the layers that should be hidden, 2 - layers that should not, 3 - simply filter annotation layer. As into the 1 approach, the list could be changed and is not static, and on another hand 2 and 3 approaches will use static data (annotation layer will always have the same name and will not depend on the spaces, templates, or parcellations.) I decided to choose from 2 and 3. Between these two, I choose the third one because I do know and didn't think that we will have some other layer types which will need to stay displayed when parcellation hides. I want also to mention that change is made into the method which is used to hide the parcellation which is already concrete enough and adding a filter for annotation would not be confusing.

2021-11-02 13:45 UTC, xgui3783 commented
I advocate for 1/ . see https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1042#issuecomment-957587934

We don't know which other layers will be added in the future (good example is for example neuromorphology mesh, which will also be hidden)

> As into the 1 approach, the list could be changed and is not static, 

that is fine. That's what rxjs is for.

2021-11-02 13:48 UTC, fsdavid commented
I see now, yes, I thought that list will need to update by hand. Sure I will make the change.

2021-11-08 18:25 UTC, xgui3783 requested changes
can you please also fix the test?

---

I am still not 100% sold on the monkey patch of `this.NgLayerObj` in pureconstant service.

I would, say, make NgLayerObj private, but implement a public method `getNgSpec(atlasId: string, templateId: string)`.

The method should return:

```ts
{
  template: NgSpec,
  segmentations: NgSpec
}
```

where `NgSpec` is defined as:

```ts
type NgLayerObj = {
  [key: string]: {
    source: string,
    type: 'segmentation' | 'image',
    ... (etc)
  }
}
```

2021-11-08 18:25 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
> +      .filter(l => Object.keys(this.pureConstantService.ngLayerObj[this.selectedTemplateId]).includes(l.name))
can you have a guard in case nglayerobj[key] is undefined?

2021-11-15 13:25 UTC, fsdavid commented
I've pushed commit with little changes from your comment.
1 - Instead of `getNgSpec(atlasId: string, templateId: string)` I've used `getNgSpec(templateId: string)` as ngLayers list does not contain atlas
2 - I'm returning only ng layers - not template

2021-11-15 13:37 UTC, xgui3783 requested changes

2021-11-15 13:37 UTC, xgui3783 commented on src/util/pureConstant.service.ts
> +  private ngLayerObj: NgLayerObj = {}
Can you add a TODO here to either improve the readability and/or remove this entirely eventually?

2021-11-15 13:37 UTC, xgui3783 commented on src/util/pureConstant.service.ts
> +  }
this can probably be simplified to:
```ts
getNgLayers(templateId: string): NgLayerObj[keyof NgLayerObj] {
  return this.ngLayerObj[templateId] || {}
}
```

2021-11-15 13:37 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +              backendUrl: `http://localhost:3000/`
I don't think `backendUrl` needs to be injected at all? if anything it should be `getNgLayers` ?

2021-11-15 13:37 UTC, xgui3783 commented on src/util/pureConstant.service.ts
> +  }
also, I think this method probably should be called `getNehubaConfigFromTemplateId`

2021-11-15 13:39 UTC, xgui3783 commented
> Instead of `getNgSpec(atlasId: string, templateId: string)` I've used `getNgSpec(templateId: string)` as ngLayers list does not contain atlas

this can easily be rectified, IMO. simply add an additional key at the top level of `ngLayerObj`?

2021-11-15 13:48 UTC, fsdavid commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +              backendUrl: `http://localhost:3000/`
Whithout `backendUrl` it returns errors again

2021-11-15 13:54 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +              backendUrl: `http://localhost:3000/`
that is very strange. I will investigate.

2021-11-15 14:16 UTC, fsdavid commented
It should work now

2021-11-15 14:16 UTC, fsdavid commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +              backendUrl: `http://localhost:3000/`
Thanks

2021-11-15 14:24 UTC, xgui3783 commented on src/util/pureConstant.service.ts
> +  getNehubaConfigFromTemplateId(atlasId: string, templateId: string) {
sorry to nitpick, this should be `getNehubaConfigFromAtlasTmplIds` now.

2021-11-15 14:27 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
> +        const layers = this.pureConstantService.getNehubaConfigFromTemplateId(this.selectedAtlasId, this.selectedTemplateId)
also, minor perf improvement ot be gained by moving this out of the filter loop

2021-11-15 14:27 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
>        .slice(1)
this is probably no longer necessary

2021-11-15 14:28 UTC, xgui3783 commented on src/util/pureConstant.service.ts
> +  getNehubaConfigFromTemplateId(atlasId: string, templateId: string) {
actually, also, can you make this function async?

2021-11-15 17:44 UTC, fsdavid commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
>        .slice(1)
Sorry, what do you mean?

2021-11-15 18:34 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
>        .slice(1)
The `.slice(1)` removes the first element in an array. 

The original logic goes something like this:

- find all layers that are visible
- toggle the visibility of all **except** the first layer (hence `.slice(1)`)

But now, with `pureService.getNehubaConfigFromAtlasTmplIds`, we no longer have to do this. We can know exactly which layers are parcellations, which layers are image.

2021-11-15 21:40 UTC, fsdavid commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.ts
>        .slice(1)
Ook thanks.

2021-11-23 09:31 UTC, merged