Add hide/show parcellation button on the chip
FZJ-INM1-BDA/siibra-explorer pull request #1157
Opened 2022-02-07 23:23 UTC by fsdavid

2022-02-07 23:43 UTC, fsdavid commented
I've commented on tests for hiding delineations. I will move them to the state if we agree about this approach.

2022-02-08 06:47 UTC, xgui3783 commented
Hmm, I have a feeling that this is way more complicated than it needs to be. 

I don't think it needs to be on the global store. The more I think about this, the more I think using a directive to track, and act on the toggle might be a simpler approach.

2022-02-09 16:09 UTC, fsdavid commented
> Hmm, I have a feeling that this is way more complicated than it needs to be.
> 
> I don't think it needs to be on the global store. The more I think about this, the more I think using a directive to track, and act on the toggle might be a simpler approach.

What do you think about the service if you do not want to make the state heavier? if we use directive it should be adapted to the element (to change icon on toggle, also tooltip will not be dynamic). Current state parcellation is will not be available in the application.

2022-02-09 16:10 UTC, fsdavid commented
or maybe we can keep only `parcellationVisible` in the state?

2022-02-09 16:34 UTC, fsdavid commented
Feature is moved to the directive

2022-02-09 17:01 UTC, xgui3783 requested changes
In general, good! This is what I had in mind when I asked you to change it to directive based.

2022-02-09 17:03 UTC, fsdavid commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +        // })
I will move it to the directive if you approve the current approach.

2022-02-09 17:07 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +        // })
I very much approve this approach ^^

2022-02-09 17:12 UTC, fsdavid commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +  }
Why don't we use a service then?

2022-02-09 17:12 UTC, fsdavid commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +    this.renderer.addClass(this.el.nativeElement, this.visible? 'fa-eye-slash' : 'fa-eye')
same as above

2022-02-09 17:35 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +  }
Hmm, my opinion is a service would have us need to inject the service in the component. This creates rather tight coupling between the host component and the service.

With a directive, the logic reside solely in the markup, and the component logic does not need to be complicated further.

2022-02-11 12:39 UTC, xgui3783 commented
@fsdavid can you ping me when you have finished this PR and it is again ready for review?

Thanks for the work so far.

2022-02-11 12:42 UTC, fsdavid commented
> @fsdavid can you ping me when you have finished this PR and it is again ready for review?
> 
> Thanks for the work so far.

Sure :)

2022-02-11 19:28 UTC, fsdavid commented
@xgui3783 I have made some changes to the tests. 
I could not make a fix  for the `'> calls schedulRedraw'` and comment it

2022-02-14 08:12 UTC, xgui3783 requested changes
Can you also remove the commit you did for `package-lock.json`?

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/nehuba/viewerCtrl/viewerCtrlCmp/viewerCtrlCmp.component.spec.ts
> +        // const toggleName = 'toggle-delineation'
can you remove if not used, rather than comment?

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +  constructor(private el: ElementRef,
I think `el` is not used anywhere?

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +              private renderer: Renderer2,
neither is `renderer`

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +      this.store$.select(viewerStateGetSelectedAtlas)
I did not know that store had a `.select` method natively. 

But still, let's keep the convention of using `.pipe(select(SELECTOR))`

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +import {Directive, ElementRef, Inject, OnDestroy, Optional, Renderer2} from "@angular/core";
I would also rename the directive to `parcVisCtrl.directive.ts` in lieu with the change of the selector

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +  exportAs: 'toggleParcellation'
I would export the directive as `sXplrParcVisCtrl`, in lieu with the updated selector

2022-02-14 08:12 UTC, xgui3783 commented on src/viewerModule/viewerStateBreadCrumb/toggle-parcellation.directive.ts
> +  }
there should no longer a need for a getter like this. all reference to the getter can be pointed to `this.nehubaInst?.nehubaViewer.ngviewer`

2022-02-15 10:19 UTC, fsdavid commented
@xgui3783 It should be fixed now

2022-02-15 10:57 UTC, xgui3783 commented
Thanks. 

I will take a look maybe today, maybe tomorrow. 

I will also investigate why `scheduleRedraw` no longer gets called.

2022-03-22 08:11 UTC, xgui3783 commented
superceded by #1169 , specifically 83b7609bfa772968e846c0c4377365dabd6e1ca0

2022-03-22 08:11 UTC, closed without merging