Integrate connectivity to sapi
FZJ-INM1-BDA/siibra-explorer pull request #1176
Opened 2022-03-13 20:11 UTC by fsdavid

2022-03-14 07:07 UTC, xgui3783 requested changes
a solid first step!

At this point I would:

- revert changes to store
- add stories so we can visualise the component in isolation

2022-03-14 07:07 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +  <connectivity-browser class="pe-all flex-shrink-1"
can you rename component & directives to something akin to:

```
sxplr-sapiviews-features-connectivity-{specifies}
```

2022-03-14 07:07 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +<!--  </connectivity-browser>-->
can you remove?

2022-03-14 07:07 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +  <div has-connectivity
re directive selector, see above naming scheme

2022-03-14 07:07 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +                        [region]="region"
Ideally it would be good to have inputs also named appropriately per above. But I am not too fussed at this stage.

2022-03-14 07:07 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +    iconClass: 'fas fa-braille',
we really need to have a better icon than `fa-braille` this is not really appropriate.

2022-03-14 07:07 UTC, xgui3783 commented on src/main.module.ts
> +  atlasAppearance,
don't worry too much about store at the moment. 

first step is to be able to adapt the connectivity browser to the new data schema.

2022-03-14 07:07 UTC, xgui3783 commented on src/viewerModule/nehuba/layerCtrl.service/layerCtrl.service.ts
> +        this.activeColorMap = returnVal
ditto above

2022-03-14 09:10 UTC, fsdavid commented on src/viewerModule/nehuba/layerCtrl.service/layerCtrl.service.ts
> +        this.activeColorMap = returnVal
Here I need 'activeColorMap' to colorise maps

2022-03-14 09:11 UTC, fsdavid commented
@xgui3783 Thanks for the review. 1 thing I've missed to make it fully functional, were `ngId`'s?

2022-03-14 09:34 UTC, xgui3783 commented
> @xgui3783 Thanks for the review. 1 thing I've missed to make it fully functional, were `ngId`'s?

I would say, do not use ngId's, but instead, use `addCustomLayer` https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/6deaf2f3dc6bacf7fea846a030c100d33c9287f1/src/state/atlasAppearance/store.ts#L38-L51 , which accepts `WeakMap<SapiRegionModel, number[]>`

it should be up to viewer (nehuba or threesurfer) to handle how to decipher the map.

2022-03-17 10:11 UTC, xgui3783 commented on src/viewerModule/nehuba/layerCtrl.service/layerCtrl.service.ts
> +        this.activeColorMap = returnVal
What I mean is don't worry about colorising maps at this stage. 

First step is to render the component, with output set up correctly.

2022-04-26 00:21 UTC, fsdavid commented
Moved here: https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1184

2022-04-26 00:21 UTC, closed without merging