Refactor migrate connectivity - change datasets with slider
FZJ-INM1-BDA/siibra-explorer pull request #1189
Opened 2022-05-04 14:08 UTC by fsdavid

2022-05-05 08:19 UTC, xgui3783 requested changes
Thanks for the PR. Mostly cosmetic changes in the code. 

Some additionall things:

- can you remove the place holder connectivity matrix component, as well as the stories associated with it
- connectivity component does not seem to play well in stories:
  - https://siibra-explorer.apps-dev.hbp.eu/refactormigrateconnectivity2/storybook-static/?path=/story/atlas-components-sapi-views-core-region-region-rich-region--injection-simple-region
  - https://siibra-explorer.apps-dev.hbp.eu/refactormigrateconnectivity2/storybook-static/?path=/story/atlas-components-sapi-views-features-connectivity-connectivity-browser-example-connectivity--default

can you take a look why?

2022-05-05 08:19 UTC, xgui3783 commented on .storybook/preview.js
> +import * as ConnectivityComponent from 'hbp-connectivity-component/dist/loader'
Hmm, I wonder if we could use unpkg rather than include it as a dependency. 

see `src/index.html` and how `ng-layer-tune` is included

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapi/core/sapiParcellation.ts
> +  getFeatures(param?: PaginationQuery, type?: string, queryParam?: SapiQueryParam): Observable<SapiParcellationFeatureModel[]> {
I would create a new type, extending the PaginationQuery, called ParcellationPaginationQuery, which contains `type: string` as an optional param

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapi/core/sapiParcellation.ts
> +        size: param && param.size? param.size.toString() : '5',
this can probably be:

`size: param?.size?.toString() || '5'`

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapi/sapi.service.ts
> +
do not hard code the URLs.

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/module.ts
> +    SapiViewsFeaturesModule,
already imported, this is not needed

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.component.ts
> +    this.expandedPanel = ''
makes more sense if `this.expandedPanel = null`

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +    contentAttribute: {types: hasConnectivityDirective.availableModalities, defaultProfile: hasConnectivityDirective.defaultProfile},
`contentAttribute` is not used anywhere? in which case remove it?

2022-05-05 08:19 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +</ng-template>
I think there is already a fallback near the header, and thus this can be removed

2022-05-05 11:26 UTC, fsdavid commented on .storybook/preview.js
> +import * as ConnectivityComponent from 'hbp-connectivity-component/dist/loader'
I could not make it work with importing on `index.html` or `.storybook/preview-head.html`
Other issues are fixed

2022-05-09 06:49 UTC, xgui3783 requested changes

2022-05-09 06:49 UTC, xgui3783 commented on src/atlasComponents/sapi/core/sapiParcellation.ts
> +
Hmm, I think what I meant originally is:

```ts
type ParcellationPaginationQuery = {
  type?: string
} & ParcellationPaginationQuery
```

so that in `getFeatures`, you will only need one additional argument.

2022-05-09 06:49 UTC, xgui3783 commented on src/atlasComponents/sapi/sapi.service.ts
> +  static modalitiesEndpoint = `https://siibra-api-dev.apps-dev.hbp.eu/v1_0/modalities`
this is actually not what I meant. 

Imagine now that we change the URL, and it is no longer at `https://siibra-api-dev.apps-dev.hbp.eu`, but at `https://siibra-api.ebrains.eu`

The current implementation means that we will need to change the end point at two separate places, and prone to error. 

`SAPI.bsEndpoint` should be the only place where the hostname, version etc is referenced, and instances where the endpoint is used simply need to reference the `SAPI.bsEndpoint`

In our case, we can simply have:

```typescript
getModalities(){
  return this.http.get(`${SAPI.bsEndPoint}/modalities`)
}
```

2022-05-09 06:49 UTC, xgui3783 commented on src/atlasComponents/sapi/sapi.service.ts
> +    return this.http.get(SAPI.modalitiesEndpoint)
ditto, please see above

2022-05-09 06:49 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.stories.ts
> +  constructor(private sapi: SAPI, private cdf: ChangeDetectorRef) {
cdf not used anywhere? 

Not overly concered, but good to know if it was injected via error

2022-05-09 06:51 UTC, xgui3783 requested changes
I __think__ you also need to import your component in `preview-head.js`

2022-05-11 07:59 UTC, fsdavid commented on src/atlasComponents/sapi/core/sapiParcellation.ts
> +
By adding the same type I'm getting an error `Type alias 'ParcellationPaginationQuery' circularly references itself.`

2022-05-11 08:02 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.stories.ts
> +  constructor(private sapi: SAPI, private cdf: ChangeDetectorRef) {
no, actually I missed adding manual detection of web component changes.

2022-05-11 08:03 UTC, fsdavid commented on src/atlasComponents/sapi/sapi.service.ts
> +  static modalitiesEndpoint = `https://siibra-api-dev.apps-dev.hbp.eu/v1_0/modalities`
> preview-head.js

Sorry, you mean preview-head.html yes?

2022-05-11 08:04 UTC, fsdavid commented
> 

Sorry, you mean `preview-head.html` yes?

2022-05-11 12:37 UTC, fsdavid commented
Moved here: https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1192

2022-05-11 12:37 UTC, closed without merging