Refactor connectivity migration to sapi
FZJ-INM1-BDA/siibra-explorer pull request #1192
Opened 2022-05-11 12:37 UTC by fsdavid

2022-05-12 06:58 UTC, xgui3783 requested changes
Just one change, otherwise, looks great.

2022-05-12 06:58 UTC, xgui3783 commented on src/atlasComponents/sapi/type.ts
> +  type?: string
`type` should not be in `SapiQueryParam`. 

We should rename the `SapiQueryParam`, too, since it is a little misleading. (It is my fault). 

It should be `SapiQueryPriorityArg` or something like that. 

`type` should be a part of `params` (same place where `page` and `per_page` are passed), since it gets serialized into query param.

2022-05-12 07:26 UTC, xgui3783 commented on src/atlasComponents/sapi/type.ts
> +  type?: string
some addendum, after looking closer at the code:
- `type` shouldn't be here (per current comment)
- priority probably shouldn't be an optional param
- type name `SapiQueryParam` is misleading (per current comment)
- `type` key val actually relate to `ParcellationPaginationQuery` (see my comment above)

2022-05-12 07:27 UTC, xgui3783 commented on src/atlasComponents/sapi/core/sapiParcellation.ts
> +  getFeatures(param?: PaginationQuery, parcPagination?: ParcellationPaginationQuery, queryParam?: SapiQueryParam): Observable<SapiParcellationFeatureModel[]> {
This method should only take 2 arguments, `ParcellationPaginationQuery` and `SapiQueryParam`

`ParcellationPaginationQuery` should extend `PaginationQuery`

2022-05-17 07:02 UTC, xgui3783 reviewed
can you double check that the changes in `package-lock.json` is necessary?

2022-05-17 07:04 UTC, xgui3783 commented on src/atlasComponents/sapi/sapi.service.ts
> +import { map, shareReplay, tap } from "rxjs/operators";
imported but not used?

2022-05-17 07:05 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public atlasId: any
typing?

2022-05-17 07:05 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
typing?

2022-05-17 07:11 UTC, xgui3783 reviewed
also please add typing (as much as possible) where they are currently `any`

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public pureConnections: any
typing?

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public connectedAreas: BehaviorSubject<any[]> = new BehaviorSubject([])
typing?

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +        private store$: Store<any>,
add typing or remove `<any>`

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    changeLog(checked) {
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    getRegionWithName(region) {
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    private formatConnections = (areas) => {
typing and probably use function declaration rather than property (ie use `private formatConnections () {}` rather than `private formatConnections = () => {}`, not a huge deal, but probably more explicit)

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +    private _region: any
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +    set region(val) {
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +    private connectivityModalities: any[] = []
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +    public defaultProfile: any
typing

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +        .pipe(map((mod: any[]) => mod.filter((m: any) => m.types && m.types.find(t => t.includes('siibra/features/connectivity')))))
typing and/or add typing to `this.sapi.getModdalities()`

2022-05-17 07:11 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +              switchMap((res: any) => {
typing

2022-05-17 10:37 UTC, fsdavid commented
> can you double check that the changes in `package-lock.json` is necessary?

On my side, the `package-lock` file changes when something changes on packages (e. g. we removed the connectivity package). If you would like to ignore these changes we can add `package-lock.json` to `.gitignore`. Last times I was rolling back this file manually.

2022-05-17 10:46 UTC, xgui3783 commented
hmm removing dependency should reduce the size of package-lock.json, not
increase it, no?

On Tue, May 17, 2022 at 12:37 PM fsdavid ***@***.***> wrote:

> can you double check that the changes in package-lock.json is necessary?
>
> On my side, the package-lock file changes when something changes on
> packages (e. g. we removed the connectivity package). If you would like to
> ignore these changes we can add package-lock.json to .gitignore. Last
> times I was rolling back this file manually.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1192#issuecomment-1128707032>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AET34F5TMXSFYXA7RDBCT4LVKNZG3ANCNFSM5VUZJ5AA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-05-17 11:03 UTC, fsdavid commented
> hmm removing dependency should reduce the size of package-lock.json, not increase it, no?

I really have no idea why it has increased. I run `npm i` to accept all the package changes. I can soft reset and push new branch with rolled back package-lock, if you would like.

2022-05-17 11:04 UTC, xgui3783 commented
can you not check what's changed in your IDE?

On Tue, May 17, 2022 at 1:03 PM fsdavid ***@***.***> wrote:

> hmm removing dependency should reduce the size of package-lock.json, not
> increase it, no?
>
> I really have no idea why it has increased. I run npm i to accept all the
> package changes. I can soft reset and push new branch with rolled back
> package-lock, if you would like.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1192#issuecomment-1128730196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AET34F33X2XAOR6HS7BQJGTVKN4I3ANCNFSM5VUZJ5AA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-05-18 09:27 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
Is there any standard for dataset typing? It looks hard to type a selected dataset if we have no standards.

2022-05-18 09:41 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
Yes, there should be something in `src/atlasComponents/sapi/type.ts`... maybe  `SapiParcellationFeatureMatrixModel`?

The models do not update automatically, but can be periodically manually updated via `npm run sapi-schema` in the future (right now, it points to a local instance of siibra-api, which likely does not exist for you)

2022-05-18 10:10 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/hasConnectivity.directive.ts
> +              switchMap((res: any) => {
`SapiParcellationFeatureModel` is not correct for now. I suggest to keep `any` type for the time being and add toDo comment.

2022-05-18 10:22 UTC, fsdavid commented
Moved here: https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1194

2022-05-18 10:46 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
Unfortunately, I could not find any type in `type.ts` that could fit `selectedDataset`. `getFeatureInstance` actually returns `SapiParcellationFeatureModel` which does not have the field `description`. 
Currently, all the metadata of the dataset is returned inside the `name` field with string format and that causes the problem of typing.

2022-05-18 11:36 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
according to the [spec](https://siibra-api-dev.apps-dev.hbp.eu/v2_0/redoc#operation/get_all_global_features_for_parcellation_atlases__atlas_id__parcellations__parcellation_id__features_get), it doesn't have a `description` field, or am I understanding incorreclty?

2022-05-18 11:44 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
yes, that is the problem. It has a description inside the `name` field. as we discussed at the dev meeting it was the bug on the python side.

2022-05-18 11:49 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
the `name` attribute was wrongly populated, correct. But am I understanding correctly that you want/need a `description` field as well?

2022-05-18 11:52 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
Yes, it is used for exporting data.

2022-05-18 11:57 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
then please raise an issue at siibra-api. 

we can't fix the issue if we don't know the issue.

2022-05-18 12:01 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
It is the issue of API or python? I thought the issue was on the python side and after fixing it we would get all the data that is inside the `name` field.

2022-05-18 12:03 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
you can raise the issue at either place. 

most straight forward is at siibra-api, since siibra-explorer only interfaces with siibra-api, and let the developers of siibra-api figure out how the issue can be resolved.

2022-05-18 12:04 UTC, fsdavid commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    public selectedDataset: any
Sure, I will raise an issue on siibra-api

2022-05-18 13:16 UTC, closed without merging