Dev connectivity filter
FZJ-INM1-BDA/siibra-explorer pull request #1254
Opened 2022-11-03 15:58 UTC by fsdavid

2022-11-07 11:46 UTC, xgui3783 requested changes
I can't help but to think the logic could be simpler. 

As it stands, there are quite a few instance variables, much of which can be expressed using observables, IMO.

I will see if I can submit a PR, and we can discuss the pro/con of each.

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.spec.ts
> +    xit('> change dataset changes name and description', () => {
I don't know if the `xit` works here, since some tests are still failing...

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +} from "src/atlasComponents/sapi";
nothing was changed? except the formatting?

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    private fetchedItems = []
typing?

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
>      public selectedType: any
would be good to add type here if we are fixing it up any way

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +      // this.fetchCohorts()
remove this if it's not used?

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    selectCohort(cohort) {
typing

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +      // this.selectedSubjectIndex = this.cohortSubjects.findIndex((s, i) => i === index - 1)
remove

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +    subjectSliderChanged(index) {
typing (likely number)

2022-11-07 11:46 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +}
is this type used anywhere?

2022-11-07 11:49 UTC, xgui3783 commented
can you also:

- check why the tests are failing
- add release notes? (should be 2.8.0, since you are trying to merge into dev branch)

2022-11-08 09:12 UTC, xgui3783 commented
per daily: 
- I have resolved the conversations which I think we can skip, but mostly still remains
- I won't push a refactor for now, but I still sincerely think that the component can and should be refactored to leverage streams more than it currently already is

2022-11-08 19:12 UTC, fsdavid commented
@xgui3783 Thanks for the review. It should work now.

2022-11-09 12:58 UTC, xgui3783 commented on spec/test.ts
> +  { teardown: { destroyAfterEach: false }},
hmm have you checked why this option needs to be toggled to false for tests to pass?

2022-11-09 14:37 UTC, fsdavid commented on spec/test.ts
> +  { teardown: { destroyAfterEach: false }},
I could not find an exact answer. When it is `true`, random tests are failing. Not sure, but it could be `NGRX` store, which requires resetting of selectors in the `afterEach` blocks.

2022-11-09 14:39 UTC, xgui3783 commented on spec/test.ts
> +  { teardown: { destroyAfterEach: false }},
I would imagine `destroyAfterEach: true` would reset the selector, not the other way around, no?

2022-11-09 14:42 UTC, fsdavid commented on spec/test.ts
> +  { teardown: { destroyAfterEach: false }},
I mean it requires restoring them manually.

2022-11-09 14:46 UTC, fsdavid commented on spec/test.ts
> +  { teardown: { destroyAfterEach: false }},
Also, I do not think it is connected to connectivity at any point.

2022-11-09 15:32 UTC, xgui3783 commented on docs/releases/v2.8.0.md
> +- More detailed filter for connectivity
you need to update mkdocs.yml and package.json accordingly

2022-11-09 15:33 UTC, xgui3783 commented on src/atlasComponents/sapiViews/features/connectivity/connectivityBrowser/connectivityBrowser.component.ts
> +} & SapiParcellationFeatureModel
updated `SapiParcellationFeatureModel` schema should contain all these fields.

2022-11-11 11:33 UTC, xgui3783 commented
@fsdavid some summary:

1/ the failing tests is (most likely) due to incompatible expectation of siibra-api version. On the UI, it will show a snack bar message re: incorrect siibra-api version, but in tests, the test could be destroyed before the snackbar is dismissed. This is likely what's causing the tests failing. (Injector destroyed ...) see #1260 

2/ There were some outdated schema relating to siibra-api (see https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1254#discussion_r1018094185) . In the future, when this happens, you could repopulate the schema. I have also added how this can be done at https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/5dedb68749da5832fb4696eba2eba23fcf649515/src/atlasComponents/sapi/README.md

2022-11-11 12:29 UTC, fsdavid commented
Thanks for the info :)

2022-11-11 13:32 UTC, merged