Multi region selection
FZJ-INM1-BDA/siibra-explorer pull request #1255
Opened 2022-11-07 18:23 UTC by fsdavid

2022-11-09 16:04 UTC, xgui3783 commented
some UI feedbacks:

chip for multi region selection should exist (currently it's missing)

header banner for multi region selection should exist (currently it does not)

rather than have the detail for which regions are select as a list under expandable menu, I think have them as chips inside header banner makes more sense. 

URL encoding seems a bit weird. I was pretty we set up the encoding scheme allowing for multiple ngIds to be grouped. Currently, we have this `r:_d238531::6y::_d238531::2P`, notice how the ngId is repeated?

2022-11-11 12:22 UTC, fsdavid commented
Thanks for the comment, I will make the changes.

2022-12-02 18:18 UTC, xgui3783 requested changes
I really don't feel comfortable modifying `region.base.directive.ts`

its purpose should be singular, accepts a single region as input, and it forms the basis of more complex components.

I think a different (or perhaps generic) view wrapper for multiple regions is more suitable.

2022-12-02 18:18 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/region.base.directive.ts
> +
I don't think we should introduce the concept of multiregion selection in any region based components (in this case, `region.base.directive.ts`

2022-12-02 18:18 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/region.base.directive.ts
> +
see above

2022-12-02 18:18 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/region.base.directive.ts
> +
see above

2022-12-02 18:18 UTC, xgui3783 commented on src/atlasComponents/sapiViews/core/region/region/rich/region.rich.template.html
> +
see above

2022-12-02 18:18 UTC, xgui3783 commented on src/viewerModule/viewerCmp/viewerCmp.template.html
> +        <!-- <mat-chip *ngFor="let region of selectedRegions$ | async"></mat-chip> -->
Don't comment, just remove

2022-12-02 18:18 UTC, xgui3783 commented on src/viewerModule/viewerCmp/viewerCmp.template.html
> +      <!-- <ng-template [ngIf]="selectedRegions.length"> -->
don't comment, just remove

2022-12-02 18:18 UTC, xgui3783 commented on src/viewerModule/viewerCmp/viewerCmp.template.html
> -      </ng-template>
Rather than reusing `sxplr-sapiviews-core-region-region-rich`, I would argue create a new view wrapper for multiple region (or perhaps, even more generic). 

such view wrappers can be used here

2023-05-10 18:34 UTC, xgui3783 commented
superceded by #1318

2023-05-10 18:34 UTC, closed without merging