Dev adding annotation
FZJ-INM1-BDA/siibra-explorer pull request #951
Opened 2021-05-18 13:23 UTC by fsdavid

2021-05-18 15:07 UTC, xgui3783 requested changes

2021-05-20 08:23 UTC, xgui3783 commented
@fsdavid  Can you convert this PR to draft? when  ready, convert it to PR, and I can go through and give reviews?

2021-05-20 08:50 UTC, fsdavid commented
> @fsdavid Can you convert this PR to draft? when ready, convert it to PR, and I can go through and give reviews?

Sure

2021-05-25 15:35 UTC, xgui3783 commented
feedback at d5ca35a:

- top right
  - icons should still be available (those not available should be disabled)
  - `annotation mode x` feels out of place 
    - use standard component (panel/card)
    - use larger font
    - x should be `mat-icon-button[color="warn"]`
  - should not be pushed when the side nav toggles
- side nav
  - point/line icon is pushed off:
    ![Screenshot from 2021-05-25 17-25-25](https://user-images.githubusercontent.com/19381783/119524794-3c4adc00-bd7e-11eb-863c-19f9a272222c.png)
  - when text field is focus -> esc should not collapse side nav
  - cannot clear landmark name (on clear, new one is automatically populated)
  - allow `alt + enter` to defocus (also related, esc should only defocus, rather than collapse side bar)
  - horizontal rule separating `select` | `point` , `line`, `poly line` | `delete` | `exit`
- missing feature
  - export to sands compatible format
  - import sands compatible format
- bug
  - drag on perspective view moves annotation as well as perspective view

2021-05-28 10:41 UTC, fsdavid commented
Thanks for your feedback. 
I have some questions:
Could not understand what do you mean - `icons should still be available (those not available should be disabled)`
Could not reproduce - `point/line icon is pushed off`
Could not understand what do you mean: `allow alt + enter to defocus` (I've added `esc` to defocus input fields)

What about `drag on perspective view moves annotation as well as perspective view` - Do you know if it is possible to get or change perspective view orientation?

2021-05-28 10:50 UTC, xgui3783 commented
> Could not understand what do you mean: allow alt + enter to defocus (I've added esc to defocus input fields)

I mean `ctrl + enter`, fixed in the comment

2021-05-28 10:51 UTC, xgui3783 commented
> Could not understand what do you mean - icons should still be available (those not available should be disabled)

I am thinking about user login/logout button, user setting, siibra-explorer about page, etc

2021-05-28 10:52 UTC, xgui3783 commented
> Could not reproduce - point/line icon is pushed off 

can you show what side nav looks like in your local installation?

2021-05-28 11:01 UTC, fsdavid commented
> > What about drag on perspective view moves annotation as well as perspective view - Do you know if it is possible to get or change perspective view orientation?
> 
> I believe so, how are you disabling translation of slice view? it should be exactly the same as preventing translation of the perspective view.

I'm getting the current state of the viewer (var name: `this.navState`), when dragging is started and while dragging I'm running: `this.interactiveViewer.viewerHandle.setNavigationLoc(this.navState)`

2021-05-28 11:02 UTC, fsdavid commented
> > Could not reproduce - point/line icon is pushed off
> 
> can you show what side nav looks like in your local installation?

![image](https://user-images.githubusercontent.com/26521731/119974474-fb88d800-bfb4-11eb-9539-7348a565742d.png)

2021-05-28 11:06 UTC, xgui3783 commented
can you check the navside bar is behaving similarly for you on 

https://quick-tour-demo.okd-dev.hbp.eu/

?

2021-05-28 11:07 UTC, fsdavid commented
> > Could not understand what do you mean - icons should still be available (those not available should be disabled)
> 
> I am thinking about user login/logout button, user setting, siibra-explorer about page, etc

Yeah, if you prefer we can show and disable them - if it will not be confusing for the users (users could think that app got stuck)

2021-05-28 11:09 UTC, xgui3783 commented
> Do you mean for description? or for all the fields? what about use ctrl + enter for description and just enter for input fields?

all fields, per trello behaviour

2021-05-28 11:16 UTC, xgui3783 commented
> > can you check the navside bar is behaving similarly for you on
> > https://quick-tour-demo.okd-dev.hbp.eu/
> > ?
> 
> Yeah sure:
> ![image](https://user-images.githubusercontent.com/26521731/119975312-faa47600-bfb5-11eb-904e-85885ec48134.png)

OK my browser renders it differently

We need to inspect it properly.

2021-05-28 11:41 UTC, xgui3783 commented
i just checked FF, it's even worse:

![Screenshot from 2021-05-28 13-40-37](https://user-images.githubusercontent.com/19381783/119978807-5d980c00-bfba-11eb-9767-00385c6f53e3.png)

2021-05-28 11:43 UTC, fsdavid commented
> i just checked FF, it's even worse:
> 
> ![Screenshot from 2021-05-28 13-40-37](https://user-images.githubusercontent.com/19381783/119978807-5d980c00-bfba-11eb-9767-00385c6f53e3.png)

It works well on my firefox. Could you please check what is hovering icons?

2021-05-28 11:46 UTC, xgui3783 commented
> Could you please check what is hovering icons?

can you elaborate how I can look for it?

2021-05-28 11:51 UTC, fsdavid commented
> > Could you please check what is hovering icons?
> 
> can you elaborate how I can look for it?

Just with selecting element which is hovering icons from dev tools 
![image](https://user-images.githubusercontent.com/26521731/119979861-c469f500-bfbb-11eb-9ece-fa4999c1b9e4.png)

2021-05-28 11:55 UTC, xgui3783 commented
I mean, from chrome element inspector, the layout is completely busted

![Screenshot from 2021-05-28 13-54-59](https://user-images.githubusercontent.com/19381783/119980250-540fa380-bfbc-11eb-89b3-695b20e0a7bf.png)

2021-05-28 11:59 UTC, fsdavid commented
> I mean, from chrome element inspector, the layout is completely busted
> 
> ![Screenshot from 2021-05-28 13-54-59](https://user-images.githubusercontent.com/19381783/119980250-540fa380-bfbc-11eb-89b3-695b20e0a7bf.png)

Thanks, I will try to make a different approach

2021-05-28 13:53 UTC, fsdavid commented on src/atlasViewer/atlasViewer.apiService.service.ts
> +
can you elaborate?

2021-05-28 14:08 UTC, xgui3783 commented on src/atlasViewer/atlasViewer.apiService.service.ts
> +
apiService should only be used for api calls, from plugins etc. 

for something internal, you can inject clickInterceptor yourself, and intercept mouse clicks

see https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/2992d9959ba9a0c9f75139e5fb006740f01a4d47/src/atlasViewer/atlasViewer.apiService.service.ts#L160-L165 for implementation detail

2021-05-30 17:44 UTC, fsdavid commented on src/atlasViewer/atlasViewer.apiService.service.ts
> +
Thanks for explanation

2021-06-01 08:24 UTC, xgui3783 requested changes
in general, there are still a lot of issues with how the code is structured. 

in particular annotationService and annotationMode component.

2021-06-01 08:24 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
> +              && annotation.position2.split(',').length !== 3) || !annotation.position1.split(',').every(e => !!e))) {
this part is not very clear at all

it'd be a lot clearer if it is broken into four separate if statement and return if conditions are unmet.

2021-06-01 08:24 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationService.service.ts
> +    public pureAnnotationsForViewer = []
typing please.

the variable name needs to be clearer also, IMO.

2021-06-02 10:19 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
Unfortunately automatic width changes after adding the first annotation and toolbar hides. What do you think could be done here?

2021-06-02 10:22 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
Yes, angular material input has some advantages but is very not in place in this situation, so I recommend keeping the current approach.

2021-06-02 10:23 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
it is related to https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/951#discussion_r642842717

2021-06-02 10:25 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
you mean auto-expand annotation into the list when the user hovers it on the viewer? would not it too much automatic changes of UI?

2021-06-02 10:31 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationService.service.ts
> +    refreshAnnotationFilter(filter = null) {
filtering annotations is not connected only to what users see but also is used for exporting. So to say it is finalized list. Also, I think it is more performant to avoid multiple filters

2021-06-02 10:48 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
like every other mat-drawer `class="box-shadow-none border-0 pe-none bg-none col-10 col-sm-10 col-md-5 col-lg-4 col-xl-3 col-xxl-2"`

2021-06-02 10:56 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
I think I know what you mean by 

> is not in place

It is how trello, for eg. deal with editing. I feel somewhat hesitant implementing trello editing style, for the following reasons:

- in trello, single click on column title has a single function -> edit
- in siibra-explorer, single click on column title, user may wish to expand the panel, or edit the name. It is ambiguous. 

I think a much natural expectation is user are able to edit name, desc, position in expanded panel, but the only functionality of the header to expand or collapse the body fo the panel

2021-06-02 10:56 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
see response above

this should use relative sizing, or flexbox

2021-06-02 11:00 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
I think I misunderstood this css.

I think we can add a `[lighter-bg]` in `theme.scss` to cover similar use cases.

there is already a `[darker-bg]`

alternatively, we could use `elevation` or `color=primary` to highlight the hovered annotation

2021-06-02 11:11 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationService.service.ts
> +    refreshAnnotationFilter(filter = null) {
Hmm, it is still quite unclear what the best way to approach this is. 

We can perhaps leave this issue for now. Once we clear up other issues, perhaps we can revisit this issue.

2021-06-02 11:33 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.template.html
> +            <mat-expansion-panel-header [ngClass]="ans.hoverAnnotation?.id.includes(annotation.id) && 'hovering-header'">
could you please elaborate?

2021-06-02 11:52 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
Yeah, I understand, column header in Trello or apps like that are also used for dragging, but I think the current approach looks better. In my opinion editing name or coordinates are not key features as just exploring data, that's why I've avoided the standard input components. UI would too be crowded and looking unnatural if there with standard inputs.

2021-06-02 12:08 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.template.html
> +            <mat-expansion-panel-header [ngClass]="ans.hoverAnnotation?.id.includes(annotation.id) && 'hovering-header'">
I think when I commented, I imagined each annotation can have its own component to separate the concerns.

probably also allow the annotation to be modelled more closely

2021-06-02 12:11 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.style.css
> +}
The concern I have is, right now, the behaviour is confusing. 

when one clicks the annotation name, it sometimes toggle the expansion panel, it sometimes doesn't. I feel this is an anti pattern.

To me, it feels more right to remove the trello like interactions altogether, and just have material inputs/textarea in expanded panel.

2021-06-02 19:42 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
> +  navigate(positionString: string) {
this shouldn't be a string, it should be `[number, number, number]`

2021-06-02 19:44 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
I think we can reuse the `key-down-lsitener` directive.

the functionality is very similar

2021-06-02 19:46 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/directives/annotationSwitch.directive.ts
> +  constructor(private store$: Store<IavRootStoreInterface>) {
the `IavRootStoreInterface` typing is ... very outdated.

we should update the typing, but for now, it's safer to type it to `any`

2021-06-02 19:46 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/directives/annotationSwitch.directive.ts
> +  }
either set this is private, or move into `onClick`

2021-06-02 19:50 UTC, xgui3783 commented on common/constants.js
> +    USER_ANNOTATION_STORE_KEY: `user_landmarks_demo_2`
hmm... I don't believe these belong here?

they should be in `component.ts`

If i told you otherwise, shows how much I know =p

2021-06-02 19:52 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
typing for annotation?

I don't know if `annotation.position1` is a `string` or `number[]`

2021-06-07 15:08 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
Here it could be both. We convert to `number[]` if it is a string. That is one of the reasons why we have `saveAnnotation` method inside `annotationList` component and are not using the service method directly.

2021-06-07 15:09 UTC, fsdavid commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
I'm not sure which listener you mean. `iav-key-listener` does not work samely

2021-06-07 15:11 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
not yet, clearly. But with some modifications, they should work similarly

2021-06-07 15:13 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
This is very confusing, and should be avoided.

I am currently working on an experimental feature that breaks the annotation service into the individual components.

Hopefully, this issue should also be fixed.

2021-06-07 15:44 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
Individual components are great, but that should not be very confusing anyways. The user modifies coordinates as a string and it needs to be converted to a number array.

2021-06-07 15:45 UTC, fsdavid commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
`not yet, clearly.` - I suggest keeping the current directive for the time being.

2021-06-07 15:50 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
it should be transformed to `number[]` before passing to this function. 

functions should be as simple as possible, doing one thing and one thing only. this would make testing and debugging significantly easier.

2021-06-07 15:51 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
adding code is easy, removing code is difficult. 

It makes no sense to end up have 2 directives doing 90% of the same things.

2021-06-07 16:14 UTC, fsdavid commented on src/atlasComponents/userAnnotations/annotationList/annotationList.component.ts
>    saveAnnotation(annotation, singlePolygon = false) {
you are right. Here the function name is most confusing. I hope we will move that function to an individual component.

2021-06-07 16:17 UTC, fsdavid commented on src/atlasComponents/userAnnotations/directives/keyListener.directive.ts
> +}
Sure, could you please link them. I just wanted to avoid outside changes as much as possible for this branch. And currently could not find the working method.

2021-06-10 09:20 UTC, xgui3783 commented
left TODOs:

- [ ] migrate tools to modular classes
  - [ ] point
  - [ ] line
- [ ] render annotations in side bar
- [ ] remove annotation.service and most code in annotationMode.component

2021-06-10 11:11 UTC, xgui3783 commented
re: double click/right click cancel editing, is there a precedent for this behaviour? like photoshop or inkscape that uses this shortcut?

2021-06-10 11:29 UTC, fsdavid commented
> re: double click/right click cancel editing, is there a precedent for this behaviour? like photoshop or inkscape that uses this shortcut?

Sure for double click. You can check `boxy-svg.com`, `editor.method.ac` and I believe many many more. For me, the normal behaviour for finishing the same type of `drawing` is by double click (It is not necessary to be a real double click I believe we can finish drawing by clicking on the last or the first point).  Right-click is Timos suggestion.

2021-06-10 12:18 UTC, xgui3783 commented
> Sure for double click. You can check boxy-svg.com, editor.method.ac

The DblCl behaviour are incredible inconsistent between these two applications.

- boxy-svg adds last point, and but does not complete the polyline
- editor.method.ac completes the last point, and completes the polyline
- for editor.methods.ac, click on any previously added point also completes polyline
- I cannot find an example where RightCl completes the polyline (we should serious consider if right click should be a mode of interaciton)

We should probably ask some feedback from sebastian and andrea.

2021-06-10 13:38 UTC, fsdavid commented
@xgui3783 Sorry but I could not understand what do you mean. I just googled first SVG editor apps and what I have able to test all of them I could finish `blazier` or any `pan` paintings with point

> > Sure for double click. You can check boxy-svg.com, editor.method.ac
> 
> The DblCl behaviour are incredible inconsistent between these two applications.
> 
> * boxy-svg adds last point, and but does not complete the polyline
> * editor.method.ac completes the last point, and completes the polyline
> * for editor.methods.ac, click on any previously added point also completes polyline
> * I cannot find an example where RightCl completes the polyline (we should serious consider if right click should be a mode of interaciton)
> 
> We should probably ask some feedback from sebastian and andrea.

Sorry but I do not understand what do you mean by `complete the polyline` and sorry if examples were not enough, I just take the first examples in google and send them to you.

Now, I've tried more apps and websites and find out that, mostly double click is a default way to end painting polyline or bazier (click on the first point is also frequent way), and `esc` removes the full editing polygon. 

App: `inkscape`, `Paint S`, `Paint pad light`. 
Web: `https://web.autocad.com/`, `https://www.photopea.com/` - Try `Polygonal Lasso Select`,  `https://pixlr.com/e/#editor`, `https://gojs.net/latest/extensions/PolygonDrawing.html`, `https://www.gifgit.com/image/pen-tool` , `https://roomstyler.com/`

I also tried Adobe XD where double click is not a default way to finish painting, but I guess because double click has another feature which is logical.

I'm still installing some apps to test but for now, my PC went crazy and stucked :d

2021-06-10 13:55 UTC, fsdavid commented
No, I'm wrong with `https://web.autocad.com/`. because it is really very slow on my PC. I tried `ARC` and double click was working but I found `pline` where it finishes with `Esc` and `Context menu`. I'm not sure why because it is very slow and I could not test well.

2021-06-10 14:30 UTC, xgui3783 commented
I mean, the fact that we are discussing what is the best way to end a poly line drawing tells me that anything other than escape is unintuitive.

2021-06-20 20:21 UTC, merged