Adding annotation line
FZJ-INM1-BDA/siibra-explorer pull request #958
Opened 2021-06-14 23:44 UTC by fsdavid

2021-06-15 07:03 UTC, xgui3783 requested changes
I haven't ran it locally, but some comments already. 

I have made some minor changes to the `registerTool` function call, but it shouldn't be too difficult to patch. 

I can assist with that.

2021-06-15 07:03 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/tools/line.ts
> +        }
this doesn't work, probably because comment above

2021-06-15 09:38 UTC, fsdavid commented on src/atlasComponents/userAnnotations/tools/line.ts
> +  }
It's because when the user clicks viewer we need already to add line, so I decide to add both points into the same place

2021-06-15 09:38 UTC, fsdavid commented on src/atlasComponents/userAnnotations/tools/line.ts
> +        } else {
`firstPoint` is added just to check if we have while annotation creation proccess

2021-06-15 09:39 UTC, fsdavid commented on src/atlasComponents/userAnnotations/tools/line.ts
> +        }
yeah, seems you are right

2021-06-15 11:16 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/tools/line.ts
> +  }
Hmm, I disagree. 

There is a big difference bewteen

```
this.points = [ptA, null]
```

and 

```
this.points = [ptA, ptA]
```

first explicitly implies that the line is not yet complete. Second implicitly mean that user picked the same point for the start and end.

2021-06-15 11:17 UTC, xgui3783 commented on src/atlasComponents/userAnnotations/tools/line.ts
> +        } else {
Then it can be boolean, doesn't need to be a `Point` ?

2021-06-18 09:12 UTC, xgui3783 commented
@fsdavid I will merge this first into dev_annotation, since there are some changes which will benefit the dev_annotation branch.

feel free to continue review the code, and add your comments either here or in dev_annotation, and ping me

2021-06-18 09:12 UTC, merged