Quick tour changes
FZJ-INM1-BDA/siibra-explorer pull request #960
Opened 2021-06-28 21:17 UTC by fsdavid

2021-06-28 21:56 UTC, xgui3783 requested changes

2021-06-28 21:56 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +  @Input('quick-tour-check-auto-start') quickTourCheckAutoStart: boolean
Probably shouldn't be in this directive

2021-06-28 21:56 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +import {LOCAL_STORAGE_CONST} from "src/util/constants";
Probably should not be in this directive. Maybe in service?

2021-06-28 21:56 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +    if (this.quickTourCheckAutoStart) {
Ditto above, probably should be in service?

2021-06-28 21:56 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
Also, shouldn't start tour without explanation. Give modal, ask if user wants a quick tour

2021-06-28 21:56 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +import {LOCAL_STORAGE_CONST} from "src/util/constants";
Also, did you use the wrong constant?

2021-06-28 22:03 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +  @Input('quick-tour-check-auto-start') quickTourCheckAutoStart: boolean
Which approach would you suggest we could use. We need to start a quick tour automatically, but only after the first ordered directive will be registered. So I decide to keep a quick tour service module local and add the input parameter `quick-tour-check-auto-start`.

2021-06-28 22:03 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +import {LOCAL_STORAGE_CONST} from "src/util/constants";
Sorry could not udnerstand

2021-06-28 22:06 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
I thought the logic should be when the user first visits the app, the tour will automatically appear, would not the modal be unnecessary? turning off quick tour anyways needs a single click.

2021-06-28 22:12 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +  @Input('quick-tour-check-auto-start') quickTourCheckAutoStart: boolean
Having a request modal also solves this issue, no? We will have time to have all quick tour directive initialise

2021-06-28 22:13 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
Hmm. It's very jarring (to me, anyway) if a quick tour is started without explanation.

But let's gather what existing apps do.

2021-06-28 22:20 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
From what I remember, in most applications, it is not started automatically at all, but it starts without modal in some apps. To be honest I do not remember any apps with modal asking start quick tour but I believe they exist.

2021-06-28 22:21 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +  @Input('quick-tour-check-auto-start') quickTourCheckAutoStart: boolean
Yes, it could.

2021-06-28 22:24 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
Would be ideal to have something to compare to. 

Can we list some applications ( preferably web ones) and compare?

2021-06-28 22:37 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
Could not remember exactly what applications have a quick tour. Do you remember any?

2021-06-28 22:49 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
maybe check https://zurb.com/playground/jquery-joyride-feature-tour-plugin

2021-06-29 08:12 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +import {LOCAL_STORAGE_CONST} from "src/util/constants";
aww, my bad. I was in a rush didn't see how LOCAL_STORAGE_CONST was used.

2021-06-29 08:32 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
I think that's not a good example. The product it sells is targeted at developers, and not users. 

I am looking at https://www.appcues.com/blog/the-5-best-walkthrough-examples and it seems most (at least 3/5) shows an onboarding message (e.g. Would you like to take a product tour > Go > No)

have you asked Hiba perhaps? she might know what might be a good pattern/anti-pattern?

2021-06-29 10:10 UTC, fsdavid commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
I've also tested apps from this URL and what I've found. As I see:
asana **does not** do anything after clicking get started we should click help and we can get help from the sidebar.
![image](https://user-images.githubusercontent.com/26521731/123774438-b0bcf180-d8cd-11eb-8c19-9428bd2b1535.png)

Humanity - is showing tooltips while using the app automatically There is not a quick tour, it is more tooltips but **automatic**. 

Pinterest - shows tooltips **automatically**. It marks a special place and adds toast for description
![image](https://user-images.githubusercontent.com/26521731/123774349-9be05e00-d8cd-11eb-8ec6-1df0153855d6.png)

Autopilot - **Does not** show anything. They have a creative way of teaching 
![image](https://user-images.githubusercontent.com/26521731/123774961-36d93800-d8ce-11eb-8420-957c27a7535a.png)

GoToWebinar - the only one that I found shows **modal** before starting the tour, I and guess the reason is that users should navigate between different pages while touring.

Finally, I agree with you because Humanity and  Pinterest do not have tours like us. They are displaying toasts or tooltips automatically while using the application. I will make some changes to show the modal.

2021-06-29 11:45 UTC, xgui3783 commented on src/ui/quickTour/quickTourThis.directive.ts
> +        this.quickTourService.startTour()
Hmm... it really seems a stepwise quick tour is going out of fashion. 

I really wonder why that is.

2021-07-06 07:40 UTC, fsdavid commented
@xgui3783 Welcome message has been added but could not remove `quick-tour-check-auto-start` input parameter of the directive, as this parameter is used to determine whenever viewer is loaded or not. Do you have any idea how could be better to find when the viewer will be loaded and then show the modal?

2021-07-06 07:54 UTC, xgui3783 commented
in principle, quick tour **can** be launched without viewer loading. 

We really shouldn't try to auto launch quick tour based on whether the viewer is loaded.

2021-07-06 10:44 UTC, fsdavid commented
> in principle, quick tour **can** be launched without viewer loading.
> 
> We really shouldn't try to auto launch quick tour based on whether the viewer is loaded.

Just quick tours usually appearing after the user logs in to the application and already sees the app content. in our case user needs to select atlas first to see the app. Especially, our tour is not action base (as it was in the first dev version), it is presentational and just shows the places, so I think it is necessary first to load or select an atlas and only then show tour. I was thinking about `selectedTemplate` subscription into the quick tour service, and we can `take(1)`, but I do not know if it is the better way. what do you think?

2021-07-06 10:57 UTC, xgui3783 commented
In principle I know what you mean.

But in practice, putting the attach auto-start input to quicktour this makes no sense. 

The best compromise maybe start the auto start flow when at least one quick tour this component has been attached.

2021-07-06 11:07 UTC, fsdavid commented
> In principle I know what you mean.
> 
> But in practice, putting the attach auto-start input to quicktour this makes no sense.
> 
> The best compromise maybe start the auto start flow when at least one quick tour this component has been attached.

yeah before I push the changes, I try the same but seems the first directive is registering too early (on the splash screen) and it makes no sense. The result was: 
There are 2 ways the user opens a app: 1 - user goes to the website landing page and 2 - user directly goes to the selected template page. at the 1 way, the dialog is shown and it makes no sense. And 2 - here user sees the first splash screen with white dialog, and after several seconds same dialog changes to a black color and it did not look nice.

2021-07-06 11:11 UTC, xgui3783 commented
> yeah before I push the changes, I try the same but seems the first directive is registering too early 

Either these quick tours needs to be conditionally rendered when viewer renders, or be attached to other elements, IMO then.

2021-07-06 11:16 UTC, fsdavid commented
> > yeah before I push the changes, I try the same but seems the first directive is registering too early
> 
> Either these quick tours needs to be conditionally rendered when viewer renders, or be attached to other elements, IMO then.

What do you think to simply watch on the selected template before we show the modal?

2021-07-06 11:21 UTC, xgui3783 commented
which components have quick tour this attached, before viewer is instantiated?

2021-07-06 11:34 UTC, fsdavid commented
The last one, plugins and tools icons one and one for selected parcellation chips

2021-07-06 11:50 UTC, xgui3783 commented
the last one can be fixed, so that it will only show when a viewer is present, but that is less relevant.

select parcellation chips - this should **not** be init when viewer is not init'ed. the chip holder is not even visible.

plugins and tools icon:

- should plugin/tool UI be visible when viewer has not yet been initiated?
- if so, should there be a quick tour step for it?

2021-07-06 11:52 UTC, fsdavid commented
> * should plugin/tool UI be visible when viewer has not yet been initiated?
> * if so, should there be a quick tour step for it?

I think the answer to both questions are yes

2021-07-06 11:56 UTC, xgui3783 commented
Then, to me, it makes logical sense that the auto start should start, with a single quick tour card pointing at the tool/plugin

Hmm, but perhaps we could introduce an input `quick-tour-severity`: 'low' | 'medium' | 'high' (probably use proper Enum)

if the only registered quick tour direcitves are of low severity, auto start will not trigger. etc etc

2021-07-06 11:57 UTC, xgui3783 commented
in this case, both the tool/icon quick tour & end card can be 'low' in severity. the rest being default severity ('medium')

2021-07-06 12:38 UTC, fsdavid commented
Nice solution. New commit should contain severity.

2021-07-06 13:56 UTC, xgui3783 commented
I have some minor tweaks to make. But I also think this is a good solution.

On Tue, 6 Jul 2021, 14:38 fsdavid, ***@***.***> wrote:

> Nice solution. New commit should contain severity.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/960#issuecomment-874723186>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AET34FYEFWTEUYBZ5NZXIIDTWL2NRANCNFSM47OY5XNQ>
> .
>

2021-07-08 09:38 UTC, merged